#!/bin/sh
# vim: set ft=sh sw=4 et :

yay -S --noconfirm yadm
yadm clone https://github.com/guemidiborhane/dotfiles.git -f --no-bootstrap -b yadm
yadm restore --staged $HOME
yadm checkout -- $HOME
yadm bootstrap
